// src/app/types/job.ts

export interface Job {
  _id: string;          // MongoDB's automatically generated ID
  userId: string;       // The ID of the user who saved it

  // 1. Core Scraped Data
  title: string;
  company: string;
  url: string;
  description: string;
  
  // 2. Kanban Dashboard Status
  status: 'Saved' | 'Applied' | 'Interviewing' | 'Offer' | 'Rejected';

  // 3. Smart Features
  matchScore: number | null;
  skills: {
    all: string[];
    matched: string[];
    missing: string[];
  };

  // 4. Details
  location: string;
  salary: string;
  tags?: string[];
  category: 'Jobs' | 'Hackathons' | 'Others';
  
  // 5. Timeline & Tracking
  deadline: string | null;     // Comes from backend as an ISO date string
  appliedDate: string | null;  // Comes from backend as an ISO date string
  postedDate: string;
  rejectionReason: string;
  history: {
    status: string;
    date: string;
  }[];
  contacts: {
    recruiterName: string;
    hiringManager: string;
  };
  notes: string;

  // 6. Timestamps (Auto-generated by Mongoose)
  createdAt: string; 
  updatedAt: string;
}
